name: CI - TaskShop
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Verificar estructura
      run: |
        echo "📁 Estructura del proyecto:"
        ls -la
        echo "📁 Contenido de src/:"
        ls -la src/
    
    - name: Ejecutar tests básicos
      run: python tests/test_basic.py
    
    - name: Verificar formato con Black
      run: black src/ tests/ --check
    
    - name: Verificar estilo con Ruff
      run: ruff check src/ tests/
    
    - name: Probar ejecución
      run: python todo_en_uno.py --help || echo "✅ Script ejecutable"

      